#!/bin/bash
#
# Copyright (c) 2017, Richard Mortier <mort@cantab.net>
# @license LICENSE.txt
#
# Deploy Mirage Xen Travis build outputs

set -e
## debug
if [[ "$DOMMAGE_DEBUG" = "true" ]]; then
  set -x
  PS4='$LINENO: '
fi

## not deploying is no error, but neither is deploying
[[ "$DEPLOY" = "false" ]] && exit 0 || true

# exit unless:
[[ "$TRAVIS_PULL_REQUEST" != "false" ]] && exit 1 # not a PR
[[ "$TRAVIS_BRANCH" != "master" ]] && exit 1      # master branch
[[ -z "$XSECRET_default_0" ]] && exit 1           # have secrets
[[ -z "$XENIMG" ]] && exit 1                      # building for Xen

declare -r XENIMG=${XENIMG:-$TRAVIS_REPO_SLUG#mirage/mirage-}.xen
declare -r MIRDIR=${MIRDIR:-src}
declare -r DEPLOYD=${TRAVIS_REPO_SLUG#*/}-deployment

sudo add-apt-repository -y ppa:avsm/ppa
sudo apt-get -qq update
sudo apt-get install -y opam && opam init -y

mkdir -p ~/.ssh
chmod 700 ~/.ssh

cat > ~/.ssh/config <<EOF
Host mirage-deploy github.com
  Hostname github.com
  StrictHostKeyChecking no
  CheckHostIP no
  UserKnownHostsFile=/dev/null
EOF
git config --global user.email 'travis@mirage.io'
git config --global user.name 'Travis the Build Bot'
git config --global push.default simple

opam install -y travis-senv
opam config exec -- travis-senv decrypt > ~/.ssh/id_dsa
chmod 600 ~/.ssh/id_dsa

git clone git@mirage-deploy:${TRAVIS_REPO_SLUG}-deployment
mkdir -p $DEPLOYD/xen/$TRAVIS_COMMIT
cp $MIRDIR/$XENIMG $MIRDIR/config.ml $DEPLOYD/xen/$TRAVIS_COMMIT
rm -f $DEPLOYD/xen/$TRAVIS_COMMIT/${XENIMG}.bz2
bzip2 -9 $DEPLOYD/xen/$TRAVIS_COMMIT/$XENIMG
echo $TRAVIS_COMMIT > $DEPLOYD/xen/latest

cd $DEPLOYD
git add xen/$TRAVIS_COMMIT xen/latest
git commit -m "adding $TRAVIS_COMMIT for $MIRAGE_BACKEND"
git status
git clean -fdx
git pull --rebase
git push
